### ISSUE TITLE
depends error

### ISSUE THREAD

**Issue by rny** [kuoruan/luci-app-v2ray#2] opened 2019-07-05 19:44 UTC
```
root@OpenWrt:/tmp# uname -r
4.9.184
root@OpenWrt:/tmp# opkg install luci-app-v2ray.ipk
Installing luci-app-v2ray (1.1.0-1) to root...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-v2ray:
 *      kernel (= 4.9.184-1-2dda2a2d0ee2eba71176fe2e0f6d5dff)
 * opkg_install_cmd: Cannot install package luci-app-v2ray.
```

fix by using 

```
root@OpenWrt:/tmp# opkg install luci-app-v2ray.ipk --force-depends
```

**Comment by kuoruan** [comment] 2019-07-07 14:17
Not a bug. Closing it.

**Closed by kuoruan** 2019-07-07 14:17 UTC
