### ISSUE TITLE
v2ray设置页面显示异常

### ISSUE THREAD

**Issue by superapple123** [kuoruan/luci-app-v2ray#106] opened 2020-02-18 13:47 UTC
你好，安装后点击“Services—v2ray”选项卡显示如下页面，无法正常使用：
Failed to execute cbi dispatcher target for entry '/admin/services/v2ray/global'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:938: module 'luci.cbi' not found:
	no field package.preload['luci.cbi']
	no file './luci/cbi.lua'
	no file '/usr/share/lua/luci/cbi.lua'
	no file '/usr/share/lua/luci/cbi/init.lua'
	no file '/usr/lib/lua/luci/cbi.lua'
	no file '/usr/lib/lua/luci/cbi/init.lua'
	no file './luci/cbi.so'
	no file '/usr/lib/lua/luci/cbi.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/luci/dispatcher.lua:938: in function </usr/lib/lua/luci/dispatcher.lua:937>

安装环境：
1、openwrt-19.07.1-x86-64-combined-ext4
2、v2ray-core_4.22.1-4_x86_64.ipk
3、luci-app-v2ray_1.5.3-1_all.ipk

目前已尝试多次反复安装，问题依然存在。将v2ray版本降级至v2ray-core_4.22.1-3_x86_64.ipk，也同样出现此问题。请问是什么原因呢？

**Comment by kuoruan** [comment] 2020-02-18 14:32
Duplicate of #42

**Closed by kuoruan** 2020-02-18 14:32 UTC
