### ISSUE TITLE
asus arch17 why this problem?

### ISSUE THREAD

**Issue by moonheadobj** [kuoruan/luci-app-v2ray#134] opened 2020-04-27 03:44 UTC
root@OpenWrt:/tmp# opkg install luci-app-v2ray_1.5.5-1_all.ipk
Installing luci-app-v2ray (1.5.5-1) to root...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-v2ray:
 *      kernel (= 5.4.35-1-35d25eaafd95b59bff2453b0d61443d9)
 * opkg_install_cmd: Cannot install package luci-app-v2ray.

**Comment by kuoruan** [comment] 2020-04-29 09:22
Duplicate of #116, #2

**Closed by kuoruan** 2020-04-29 09:22 UTC
