### ISSUE TITLE
v2ray视图问题

### ISSUE THREAD

**Issue by sebastianchuk** [kuoruan/luci-app-v2ray#164] opened 2020-05-26 12:17 UTC
操作系统19.07.3
安装文件v2ray-core_4.23.1-5_arm_cortex-a9_vfpv3-d16.ipk 
               luci-app-v2ray_1.5.6_all.ipk
安装完成以后 网页点击Services->V2ray 显示以下提示
/usr/lib/lua/luci/dispatcher.lua:1329: module 'luci.cbi' not found:
	no field package.preload['luci.cbi']
	no file './luci/cbi.lua'
	no file '/usr/share/lua/luci/cbi.lua'
	no file '/usr/share/lua/luci/cbi/init.lua'
	no file '/usr/lib/lua/luci/cbi.lua'
	no file '/usr/lib/lua/luci/cbi/init.lua'
	no file './luci/cbi.so'
	no file '/usr/lib/lua/luci/cbi.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/luci/dispatcher.lua:1329: in function '_cbi'
	/usr/lib/lua/luci/dispatcher.lua:1018: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:979: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:478: in function </usr/lib/lua/luci/dispatcher.lua:477>

**Comment by kuoruan** [comment] 2020-05-26 13:48
Duplicate of #42

**Closed by kuoruan** 2020-05-26 13:48 UTC
